"""Initial database schema fixed

Revision ID: 4cd4c3d452e6
Revises: 
Create Date: 2025-10-21 01:50:47.373888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd4c3d452e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('posts_processed', sa.Integer(), nullable=True),
    sa.Column('posts_updated', sa.Integer(), nullable=True),
    sa.Column('posts_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_jobs_job_name'), 'scraping_jobs', ['job_name'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('vas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator', sa.String(length=100), nullable=True),
    sa.Column('set_id', sa.String(length=50), nullable=True),
    sa.Column('set_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vas_name'), 'vas', ['name'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('va_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.String(length=10), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('sound', sa.Text(), nullable=True),
    sa.Column('slides', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scraping_status', sa.String(length=20), nullable=False),
    sa.Column('days_since_posted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('comments >= 0', name='check_comments_positive'),
    sa.CheckConstraint('engagement >= 0', name='check_engagement_positive'),
    sa.CheckConstraint('likes >= 0', name='check_likes_positive'),
    sa.CheckConstraint('shares >= 0', name='check_shares_positive'),
    sa.CheckConstraint('views >= 0', name='check_views_positive'),
    sa.ForeignKeyConstraint(['va_id'], ['vas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_account_date', 'posts', ['account', 'created_date'], unique=False)
    op.create_index('idx_posts_engagement', 'posts', ['engagement'], unique=False)
    op.create_index('idx_posts_va_date', 'posts', ['va_id', 'created_date'], unique=False)
    op.create_index('idx_posts_views', 'posts', ['views'], unique=False)
    op.create_index(op.f('ix_posts_account'), 'posts', ['account'], unique=False)
    op.create_index(op.f('ix_posts_created_date'), 'posts', ['created_date'], unique=False)
    op.create_index(op.f('ix_posts_post_url'), 'posts', ['post_url'], unique=True)
    op.create_index(op.f('ix_posts_source'), 'posts', ['source'], unique=False)
    op.create_index(op.f('ix_posts_va_id'), 'posts', ['va_id'], unique=False)
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_post_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('variation_1', sa.Text(), nullable=True),
    sa.Column('variation_2', sa.Text(), nullable=True),
    sa.Column('variation_3', sa.Text(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_templates_original_post_id'), 'content_templates', ['original_post_id'], unique=False)
    op.create_table('metrics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('va_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('days_since_posted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['va_id'], ['vas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'snapshot_date', name='unique_post_snapshot')
    )
    op.create_index('idx_metrics_post_date', 'metrics_history', ['post_id', 'snapshot_date'], unique=False)
    op.create_index('idx_metrics_va_date', 'metrics_history', ['va_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_metrics_history_post_id'), 'metrics_history', ['post_id'], unique=False)
    op.create_index(op.f('ix_metrics_history_snapshot_date'), 'metrics_history', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_metrics_history_va_id'), 'metrics_history', ['va_id'], unique=False)
    op.create_table('repost_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_post_id', sa.Integer(), nullable=False),
    sa.Column('repost_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('predicted_views', sa.Integer(), nullable=True),
    sa.Column('predicted_engagement', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repost_candidates_original_post_id'), 'repost_candidates', ['original_post_id'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('slide_url', sa.String(length=1000), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'slide_index', name='unique_post_slide')
    )
    op.create_index('idx_slides_hash', 'slides', ['image_hash'], unique=False)
    op.create_index('idx_slides_post_index', 'slides', ['post_id', 'slide_index'], unique=False)
    op.create_index(op.f('ix_slides_image_hash'), 'slides', ['image_hash'], unique=False)
    op.create_index(op.f('ix_slides_post_id'), 'slides', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_post_id'), table_name='slides')
    op.drop_index(op.f('ix_slides_image_hash'), table_name='slides')
    op.drop_index('idx_slides_post_index', table_name='slides')
    op.drop_index('idx_slides_hash', table_name='slides')
    op.drop_table('slides')
    op.drop_index(op.f('ix_repost_candidates_original_post_id'), table_name='repost_candidates')
    op.drop_table('repost_candidates')
    op.drop_index(op.f('ix_metrics_history_va_id'), table_name='metrics_history')
    op.drop_index(op.f('ix_metrics_history_snapshot_date'), table_name='metrics_history')
    op.drop_index(op.f('ix_metrics_history_post_id'), table_name='metrics_history')
    op.drop_index('idx_metrics_va_date', table_name='metrics_history')
    op.drop_index('idx_metrics_post_date', table_name='metrics_history')
    op.drop_table('metrics_history')
    op.drop_index(op.f('ix_content_templates_original_post_id'), table_name='content_templates')
    op.drop_table('content_templates')
    op.drop_index(op.f('ix_posts_va_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_source'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_url'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_account'), table_name='posts')
    op.drop_index('idx_posts_views', table_name='posts')
    op.drop_index('idx_posts_va_date', table_name='posts')
    op.drop_index('idx_posts_engagement', table_name='posts')
    op.drop_index('idx_posts_account_date', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_vas_name'), table_name='vas')
    op.drop_table('vas')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_scraping_jobs_job_name'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    op.drop_table('data_import_log')
    # ### end Alembic commands ###
